/**
 * كل نصوص الواجهة للمستخدم — عربية فقط، صياغة واضحة وبعيدة عن المصطلحات التقنية الثقيلة.
 */
export const t = {
  auth: {
    authHubTitle: "ابدأ مع shoot'ha",
    authHubSubtitle: "أنشئ حساباً كمالك ملعب، أو سجّل دخولك إذا كان عندك حساب مسبقاً.",
    createAccount: "إنشاء حساب",
    loginExisting: "تسجيل الدخول",
    loginTitle: "تسجيل الدخول",
    loginSubtitle: "أدخل رقم جوالك بدون المفتاح الدولي (يظهر ثابتاً بجانب الحقل) — نرسل لك رمز تحقق لمرة واحدة.",
    registerTitle: "إنشاء حساب",
    registerSubtitle: "أدخل رقم جوالك واسمك، اضغط التسجيل، ثم أدخل رمز التحقق المرسل لجوالك لإكمال إنشاء الحساب.",
    /** إنشاء حساب برقم الجوال فقط (بدون اسم في الواجهة) */
    registerSubtitlePhoneOnly:
      "أدخل رقم جوالك بصيغة دولية تبدأ بـ +، نرسل لك رمز تحقق لمرة واحدة لإكمال إنشاء حسابك كمالك ملعب.",
    registerSubtitlePhoneName:
      "اكتب اسمك الكامل ثم رقم جوالك (بدون المفتاح الدولي؛ يظهر ثابتاً). نرسل لك رمز تحقق لإكمال التسجيل.",
    fullNameLabel: "الاسم الكامل",
    fullNamePlaceholder: "مثال: محمد أحمد العتيبي",
    /** بعد الضغط: الانتقال لصفحة إدخال OTP */
    registerSubmitContinue: "التسجيل والمتابعة",
    verifyOtpRegister: "إنشاء الحساب",
    otpScreenTitleRegister: "التحقق من الرمز",
    alreadyHaveAccount: "عندك حساب؟",
    noAccountYet: "ما عندك حساب؟",
    backToAuthHub: "العودة للبداية",
    nameTooShort: "اكتب الاسم على الأقل حرفين",
    otpHeroSubtitleRegister: "أدخل رمز التحقق المكوّن من 6 أرقام. بعد التأكيد يُنشأ حسابك.",
    registerSuccess: "تم إنشاء حسابك بنجاح",
    serverVerifyFailed: "تعذّر إكمال التحقق من الخادم. جرّب مرة ثانية أو تواصل مع الدعم.",
    authHeroSubtitle: "تابع حجوزات ملعبك من مكان واحد: قبول، رفض، وتنظيم المواعيد.",
    otpHeroSubtitle: "أدخل الرمز المكوّن من ستة أرقام الذي وصلك على الجوال.",
    changePhone: "تغيير الرقم",
    welcome: "أهلاً بك — منصة ملاك الملاعب",
    guestLogin: "دخول كزائر",
    guestHint: "تقدر تتصفّح التطبيق كزائر قبل ما تربط حسابك. البيانات الحقيقية تظهر بعد ربط الخادم.",
    guestBadge: "أنت الآن زائر",
    guestExitHint: "للمتابعة بحسابك الحقيقي: اخرج ثم سجّل برقم جوالك.",
    guestModeEnabledToast: "تم تفعيل وضع الزائر",
    guestModeNoEnvToast: "لا يزال الخادم غير مفعّل — التصفح محلي فقط.",
    guestModeAnonDisabledToast: "تعذر إكمال العملية — سيتم تفعيلها عند ربط الخادم.",
    phoneLabel: "رقم الجوال",
    phonePlaceholder: "+9647700000000",
    /** الجزء الوطني فقط — المفتاح الدولي ثابت في الواجهة */
    phonePlaceholderNational: "7xxxxxxxxx",
    sendOtp: "إرسال رمز التحقق",
    enterOtp: "رمز التحقق",
    verifyOtp: "تأكيد الدخول",
    otpPlaceholderDots: "• • • • • •",
    otpSentSuccess: "تم إرسال الرمز إلى جوالك",
    otpVerifySuccess: "تم الدخول بنجاح",
    otpWrongCode: "الرمز غير صحيح",
    otpSendFailed: "ما قدرنا نرسل الرمز، جرّب مرة ثانية",
    logout: "خروج من الحساب",
    deleteAccount: "حذف الحساب",
    deleteConfirmTitle: "تأكيد حذف الحساب",
    deleteConfirmBody: "هل أنت متأكد؟ ما راح تقدر ترجع الحساب بعد الحذف."
  },
  tabs: {
    home: "الحجوزات",
    fields: "الملاعب",
    notifications: "الإشعارات",
    accounts: "المالية",
    profile: "الحساب"
  },
  fields: {
    title: "ملاعبك",
    subtitle: "بعد قبول طلب إضافة ملعب يظهر هنا. يمكنك إغلاق الملعب أو وضعه تحت الصيانة أو الحجز اليدوي.",
    emptyTitle: "لا توجد ملاعب بعد",
    emptySubtitle: "أرسل طلب إضافة ملعب من صفحة الحجوزات، وبعد موافقة الإدارة يظهر الملعب تلقائياً هنا.",
    needFirebase: "فعّل Firebase في البيئة لعرض الملاعب.",
    loadError: "تعذّر تحميل الملاعب",
    statusOpen: "مفتوح",
    statusClosed: "مغلق",
    statusMaintenance: "صيانة",
    menuTitle: "خيارات الملعب",
    actionClose: "إغلاق الملعب",
    actionMaintenance: "تحت الصيانة",
    actionOpen: "إعادة الفتح",
    actionManage: "حجز وإدارة المواعيد",
    manageHeader: "إدارة الملعب",
    selectDate: "التاريخ",
    availableSlots: "الأوقات المتاحة",
    noSlots: "لا توجد أوقات متاحة في هذا اليوم.",
    closedBanner: "الملعب مغلق — لا يمكن إضافة حجز.",
    maintenanceBanner: "الملعب تحت الصيانة — لا يمكن إضافة حجز.",
    bookingSection: "حجز يدوي",
    fieldBookingsSection: "حجوزات هذا الملعب",
    durationLabel: "المدة (دقيقة)",
    servicesLabel: "خدمات إضافية (افصل بينها بفاصلة)",
    servicesPlaceholder: "مثال: إضاءة، ماء، تسجيل",
    sourceLabel: "مصدر الحجز",
    sourceManual: "يدوي منك",
    sourcePlayer: "لاعب",
    playerNameLabel: "اسم اللاعب",
    playerNamePlaceholder: "اختياري",
    saveBooking: "تأكيد الحجز",
    bookingSaved: "تم حفظ الحجز",
    editBooking: "تعديل الحجز",
    deleteBooking: "حذف",
    confirmDeleteTitle: "حذف الحجز؟",
    confirmDeleteBody: "لن يمكن التراجع عن هذا الإجراء.",
    bookingUpdated: "تم تحديث الحجز",
    bookingDeleted: "تم حذف الحجز",
    pickSlotHint: "اختر وقتاً من القائمة أو اضبط الوقت يدوياً أدناه.",
    dashboardFieldBadge: "من لوحة التحكم",
    dashboardFieldBanner:
      "هذا الملعب يُدار من لوحة التحكم — لا يُضاف حجز يدوي من هنا. الحجوزات الظاهرة أدناه قادمة من الداشبورد.",
    dashboardSyncHint:
      "الحجز اليدوي يُحجز الوقت هنا ويُزامَن تلقائياً مع الداشبورد وتطبيق اللاعب لنفس الملعب.",
    dashboardBookingsReadOnly: "لتعديل حجوزات اللاعبين افتح تبويب الحجوزات.",
    fieldSizeShort: "الحجم",
    dashboardStatusLocked: "حالة ملاعب الداشبورد تُعدّل من لوحة التحكم فقط."
  },
  accounts: {
    title: "حساباتك المالية",
    subtitle: "وارد خارجي ويدوي، مصاريف، ووارد الشهر — البيانات محفوظة على جهازك.",
    externalTotal: "إجمالي الوارد الخارجي",
    manualTotal: "إجمالي الوارد اليدوي",
    monthlyIncome: "وارد هذا الشهر",
    expensesTotal: "إجمالي المصاريف",
    addMovement: "تسجيل حركة",
    amountLabel: "المبلغ",
    amountPlaceholder: "مثال: 150000",
    noteLabel: "ملاحظة (اختياري)",
    notePlaceholder: "وصف قصير…",
    addExpense: "إضافة مصروف",
    addIncomeExternal: "وارد خارجي",
    addIncomeManual: "وارد يدوي",
    recentTitle: "آخر الحركات",
    emptyMovements: "لا توجد حركات بعد.",
    savedToast: "تم حفظ الحركة",
    invalidAmount: "اكتب مبلغاً صحيحاً أكبر من صفر",
    currency: "د.ع",
    kindExpense: "مصروف",
    kindExternal: "وارد خارجي",
    kindManual: "وارد يدوي",
    kindBooking: "وارد من حجز"
  },
  bookings: {
    today: "اليوم",
    upcoming: "القادم",
    past: "السابق",
    addBooking: "إضافة حجز",
    requestAddField: "طلب إضافة ملعب",
    requestAddFieldTitle: "طلب إضافة ملعب جديد",
    requesterNameLabel: "اسمك",
    requesterNamePlaceholder: "الاسم الثلاثي",
    fieldNameLabel: "اسم الملعب",
    fieldNamePlaceholder: "مثال: ملعب النخيل",
    cityLabel: "المدينة أو الحي",
    cityPlaceholder: "مثال: بغداد — مطلوب لطلب الملعب",
    notesLabel: "ملاحظات",
    notesPlaceholder: "مثال: الموقع، السعة، نوع الأرضية…",
    contactPhoneLabel: "رقم التواصل",
    contactPhonePlaceholder: "للتواصل معك عند الحاجة",
    contactPhonePlaceholderNational: "7xxxxxxxxx",
    submitFieldRequest: "إرسال الطلب",
    fieldRequestSuccess: "تم إرسال طلبك بنجاح",
    fieldRequestNeedBackend: "الخادم غير مفعّل بعد — ما نقدر نرسل الطلب الحين. جرّب لاحقاً بعد التفعيل.",
    fieldRequestValidation: "اكتب اسم الملعب",
    fieldRequestValidationPerson: "اكتب اسمك",
    fieldRequestValidationLocation: "اكتب المدينة أو المنطقة (الموقع)",
    fieldRequestFirebaseNotConfigured: "Firebase غير مُعدّ — لا يمكن إرسال الطلب.",
    fieldRequestLoginRequired: "سجّل الدخول لإرسال الطلب إلى Firestore.",
    fieldRequestOwnerIdMissing: "تعذّر تحميل معرّف المالك. أعد تسجيل الدخول.",
    fieldRequestProfileIncomplete: "أكمل اسمك ورقم جوالك في الملف الشخصي لإرسال الطلب.",
    requestIdSentHint: "رقم مرجعي يُرسل مع طلبك",
    accountIdHint: "رقم حسابك يظهر للإدارة تلقائياً",
    guestPreviewAccountHint: "رقم جلسة الزائر",
    guestSessionHint: "مرجع الجلسة",
    fieldRequestTableMissing: "ما نقدر نكمل الطلب — الخدمة غير جاهزة بعد.",
    emptyTitle: "ما فيه حجوزات",
    emptySubtitle: "أي حجز جديد راح يظهر هنا.",
    approve: "قبول",
    reject: "رفض",
    statusPending: "بالانتظار",
    statusApproved: "مقبول",
    statusRejected: "مرفوض",
    statusConfirmed: "مؤكد",
    statusCancelled: "ملغى",
    fieldLabel: "الملعب",
    totalPriceLabel: "السعر",
    durationLabel: "المدة",
    currencyShort: "ر.س",
    createdByOwner: "من المالك",
    createdByPlayer: "من اللاعب",
    sourceManualLabel: "حجز يدوي",
    sourcePlayerPrefix: "من اللاعب: ",
    servicesLineLabel: "الخدمات",
    dashboardBookingSource: "حجز من لوحة التحكم",
    fieldSizeLabel: "حجم الملعب",
    paymentMethodLabel: "طريقة الدفع",
    playerPhoneLabel: "جوال اللاعب",
    venueDurationHint: "القيمة ≤٢٤ تُحسب بالساعات، وإلا بالدقائق (كما في الداشبورد)",
    venueIdLabel: "معرّف الملعب",
    venueNameLabel: "اسم الملعب",
    bookingStatusLabel: "الحالة",
    noPlayerName: "بدون اسم لاعب",
    editBookingShort: "تعديل",
    deleteBookingShort: "حذف",
    loginRequiredBookings: "سجّل دخولك برقم الجوال عشان تشوف حجوزاتك.",
    needBackendBookings: "عرض الحجوزات من الخادم غير مفعّل حالياً.",
    loadErrorBookings: "ما قدرنا نحمّل الحجوزات. تحقق من الإنترنت وحاول مرة ثانية.",
    emptyStateLoadTitle: "تعذّر عرض الحجوزات",
    emptyStateBackendTitle: "عرض الحجوزات غير مفعّل",
    noFieldsHint: "ما فيه ملعب مربوط بحسابك بعد.",
    selectField: "اختر الملعب",
    priceLabel: "السعر (ر.س)",
    bookingSaved: "تم حفظ الحجز",
    statusUpdated: "تم تحديث الحالة",
    screenSubtitle: "متابعة طلبات ملعبك",
    dateLabel: "التاريخ",
    datePlaceholder: "مثال: ٢٠٢٦-٠٤-٠٣",
    startTimeLabel: "وقت البداية",
    timePlaceholder: "مثال: ١٨:٠٠",
    durationMinutesLabel: "مدة الحجز",
    durationPlaceholder: "٦٠",
    durationOneHour: "ساعة",
    durationOneHourSub: "٦٠ دقيقة",
    durationOneHalfHour: "ساعة ونص",
    durationOneHalfHourSub: "٩٠ دقيقة",
    pricePlaceholder: "١٠٠",
    modalCancel: "إلغاء",
    modalSave: "حفظ",
    phoneRequiredForGuestRequest: "الزائر لازم يكتب رقم جوال للتواصل",
    fieldRequestSheetSubtitle: "املأ البيانات وراح نراجع طلبك ونتواصل معك.",
    fieldRequestStep1Title: "بياناتك واسم الملعب",
    fieldRequestStep2Title: "الموقع والتفاصيل",
    fieldRequestStep3Title: "التواصل والمراجعة",
    fieldRequestNext: "التالي",
    fieldRequestBack: "رجوع",
    fieldRequestGuestPhoneNote: "لازم رقم جوال عشان نتواصل معك.",
    fieldRequestSummaryTitle: "ملخص طلبك",
    fieldRequestOwnerIdLabel: "معرّف المالك (من النظام)",
    fieldRequestOwnerIdHint: "يُرسل تلقائياً مع الطلب ولا يمكن تعديله.",
    scheduleInlineTitle: "جدول اليوم",
    scheduleInlineOpen: "فتح",
    postMatchTitle: "انتهت المباراة",
    postMatchSubtitle: "قيّم اللاعب وسجّل نهاية الحجز. يُحفظ التقييم في السحابة ويُضاف سعر الحجز للمالية.",
    ratePlayerLabel: "تقييم اللاعب",
    starsHint: "من نجمة واحدة إلى خمس",
    commentLabel: "ملاحظة (اختياري)",
    commentPlaceholder: "مثال: انضباط، تعامل…",
    submitPostMatch: "حفظ التقييم وإنهاء الحجز",
    postMatchSuccess: "تم حفظ التقييم وتسجيل المبلغ في المالية",
    postMatchAlreadyDone: "تم إنهاء هذا الحجز مسبقاً",
    postMatchNotFound: "تعذّر تحميل الحجز",
    postMatchError: "تعذّر الإكمال. تحقق من الاتصال والقواعد.",
    settledBadge: "منتهٍ",
    endMatchButton: "تقييم وإنهاء",
    postMatchPickRating: "اختر عدد النجوم"
  },
  schedule: {
    title: "الجدول اليومي",
    subtitle: "كل خانة نصف ساعة — نظام الحجز: ساعة أو ساعة ونص فقط.",
    backToBookings: "رجوع للحجوزات",
    empty: "ما فيه حجوزات اليوم.",
    booked: "محجوز",
    available: "فاضي",
    slotHalfHour: "نصف ساعة"
  },
  notifications: {
    title: "الإشعارات",
    emptyTitle: "ما فيه إشعارات",
    emptySubtitle: "التنبيهات والتحديثات راح تظهر هنا.",
    loginRequiredSubtitle: "سجّل دخولك عشان تشوف إشعاراتك.",
    guestEmptyTitle: "الإشعارات غير متاحة",
    needBackendSync: "أضف مفاتيح Firebase في البيئة (EXPO_PUBLIC_FIREBASE_*) لتلقّي الإشعارات من السحابة.",
    emptyStateBackendTitle: "Firebase غير مُعدّ للإشعارات",
    loadError: "ما قدرنا نحمّل الإشعارات. حاول مرة ثانية.",
    markAllRead: "تعليم الكل كمقروء",
    allUpdatedToast: "تم التحديث",
    unreadSuffix: "غير مقروء",
    noNewAlerts: "ما فيه تنبيهات جديدة",
    typeBooking: "حجز",
    typeApproval: "موافقة",
    typeSystem: "تنبيه",
    fieldRequestApprovedTitle: "تم قبول طلب إضافة الملعب",
    fieldRequestApprovedBody: "الملعب «{name}» — يمكنك متابعة الإعداد من الحساب أو الدعم.",
    fieldRequestRejectedTitle: "تم رفض طلب إضافة الملعب",
    fieldRequestRejectedBody: "الملعب «{name}». للاستفسار تواصل مع الدعم.",
    newBookingToastTitle: "حجز جديد",
    newBookingToastSub: "اضغط للانتقال إلى الحجوزات",
    openBookingHint: "اضغط للانتقال إلى الحجز في قائمة الحجوزات",
    bookingOpenedFromNotification: "تم عرض الحجز",
    bookingNotFound: "تعذّر العثور على الحجز في القائمة بعد التحديث"
  },
  profile: {
    title: "الحساب",
    name: "الاسم",
    phone: "رقم الجوال",
    fieldName: "اسم الملعب",
    editProfile: "تعديل الحساب",
    requestFieldChange: "طلب تعديل بيانات الملعب",
    reportIssue: "إبلاغ عن مشكلة",
    darkMode: "الوضع الداكن",
    save: "حفظ",
    cancel: "إلغاء",
    dataSection: "بياناتك",
    settingsSection: "الإعدادات",
    fieldNameExample: "ملعب الحي (مثال)",
    guestName: "زائر",
    saveSuccessToast: "تم حفظ التعديلات"
  },
  requests: {
    fieldChangeTitle: "طلب تعديل بيانات الملعب",
    issueTitle: "إبلاغ عن مشكلة",
    placeholder: "اكتب التفاصيل هنا…",
    send: "إرسال",
    success: "تم إرسال طلبك"
  },
  common: {
    error: "صار خطأ غير متوقع",
    pullToRefresh: "اسحب للتحديث",
    loading: "جارٍ التحميل…",
    tryAgain: "إعادة المحاولة",
    cancel: "إلغاء",
    done: "تم"
  },
  errors: {
    backendLater: "هذه الخدمة راح تتفعّل لاحقاً مع الخادم.",
    useAuthContext: "خطأ في تهيئة الجلسة. أعد فتح التطبيق.",
    useSettingsContext: "خطأ في الإعدادات. أعد فتح التطبيق.",
    firebaseNotConfigured: "Firebase غير مُعدّ: أضف مفاتيح EXPO_PUBLIC_FIREBASE_* في ملف البيئة.",
    firebaseRecaptchaNotReady: "جاري تهيئة التحقق. حاول مرة ثانية بعد لحظة.",
    firebaseSendOtpFailed: "تعذّر إرسال رمز التحقق. تحقق من الرقم ومن إعداد Firebase.",
    firebaseOtpSessionExpired: "انتهت جلسة التحقق. ارجع وأعد إرسال الرمز.",
    phoneMustStartWithPlus: "اكتب الرقم بصيغة دولية تبدأ بـ + (مثال: +9647700000000).",
    phoneInvalidE164: "صيغة الرقم غير صحيحة. استخدم + متبوعاً بكود الدولة ثم الرقم (حتى 15 رقماً).",
    phoneNationalInvalid:
      "رقم الجوال المحلي غير صحيح. للعراق (+964): 10 أرقام تبدأ بـ 7 (مثال: 7712345678)."
  }
};
