/**
 * كل نصوص الواجهة للمستخدم — عربية فقط، صياغة واضحة وبعيدة عن المصطلحات التقنية الثقيلة.
 */
export const t = {
  auth: {
    authHubTitle: "ابدأ مع shoot'ha",
    authHubSubtitle: "أنشئ حساباً كمالك ملعب، أو سجّل دخولك إذا كان عندك حساب مسبقاً.",
    createAccount: "إنشاء حساب",
    loginExisting: "تسجيل الدخول",
    loginTitle: "تسجيل الدخول",
    loginSubtitle: "أدخل رقم الهاتف بدون المفتاح الدولي (يظهر ثابتاً بجانب الحقل).",
    registerTitle: "إنشاء حساب",
    registerSubtitle: "أدخل رقم الهاتف واسمك، اضغط التسجيل، ثم أدخل رمز التحقق المرسل لهاتفك لإكمال إنشاء الحساب.",
    /** إنشاء حساب برقم الهاتف فقط (بدون اسم في الواجهة) */
    registerSubtitlePhoneOnly:
      "أدخل رقم الهاتف بصيغة دولية تبدأ بـ +، نرسل لك رمز تحقق لمرة واحدة لإكمال إنشاء حسابك كمالك ملعب.",
    registerSubtitlePhoneName: "أدخل بياناتك لإكمال التسجيل.",
    fullNameLabel: "الاسم الكامل",
    fullNamePlaceholder: "الاسم الثلاثي",
    /** بعد الضغط: الانتقال لصفحة إدخال OTP */
    registerSubmitContinue: "التسجيل والمتابعة",
    verifyOtpRegister: "إنشاء الحساب",
    otpScreenTitleRegister: "التحقق من الرمز",
    alreadyHaveAccount: "عندك حساب؟",
    noAccountYet: "ما عندك حساب؟",
    backToAuthHub: "العودة للبداية",
    nameTooShort: "اكتب الاسم على الأقل حرفين",
    otpHeroSubtitleRegister: "أدخل رمز التحقق المكوّن من 6 أرقام. بعد التأكيد يُنشأ حسابك.",
    registerSuccess: "تم إنشاء حسابك بنجاح",
    serverVerifyFailed: "تعذّر إكمال التحقق من الخادم. جرّب مرة ثانية أو تواصل مع الدعم.",
    authHeroSubtitle: "تابع حجوزات ملعبك من مكان واحد: قبول، رفض، وتنظيم المواعيد.",
    otpHeroSubtitle: "أدخل الرمز المكوّن من 6 أرقام الذي وصلك على الهاتف.",
    changePhone: "تغيير الرقم",
    welcome: "أهلاً بك — منصة ملاك الملاعب",
    guestLogin: "دخول كزائر",
    guestHint: "تقدر تتصفّح التطبيق كزائر قبل ما تربط حسابك. البيانات الحقيقية تظهر بعد ربط الخادم.",
    guestBadge: "أنت الآن زائر",
    guestExitHint: "للمتابعة بحسابك الحقيقي: اخرج ثم سجّل برقم الهاتف.",
    guestModeEnabledToast: "تم تفعيل وضع الزائر",
    guestModeNoEnvToast: "لا يزال الخادم غير مفعّل — التصفح محلي فقط.",
    guestModeAnonDisabledToast: "تعذر إكمال العملية — سيتم تفعيلها عند ربط الخادم.",
    phoneLabel: "رقم الهاتف",
    phonePlaceholder: "+9647700000000",
    /** الجزء الوطني فقط — المفتاح الدولي ثابت في الواجهة */
    phonePlaceholderNational: "7xxxxxxxxx",
    sendOtp: "إرسال رمز التحقق",
    forgotPassword: "نسيت كلمة السر؟",
    enterOtp: "رمز التحقق",
    verifyOtp: "تأكيد الدخول",
    verifyOtpConfirm: "تأكيد",
    resendOtp: "إعادة إرسال الرمز",
    resendAfter: "إعادة إرسال الرمز خلال",
    otpPlaceholderDots: "• • • •",
    otpSentSuccess: "تم إرسال الرمز إلى هاتفك",
    otpVerifySuccess: "تم الدخول بنجاح",
    otpWrongCode: "الرمز غير صحيح",
    otpExpired: "انتهت صلاحية الكود",
    otpRetryLimit: "تم تجاوز عدد المحاولات المسموح. أعد إرسال الكود.",
    resendAfterOneMinute: "يمكنك إعادة المحاولة بعد 60 ثانية",
    otpSendFailed: "ما قدرنا نرسل الرمز، جرّب مرة ثانية",
    logout: "خروج من الحساب",
    deleteAccount: "حذف الحساب",
    deleteConfirmTitle: "تأكيد حذف الحساب",
    deleteConfirmBody: "هل أنت متأكد؟ ما راح تقدر ترجع الحساب بعد الحذف."
  },
  tabs: {
    home: "الرئيسية",
    fields: "الملاعب",
    notifications: "الإشعارات",
    accounts: "المالية",
    profile: "الحساب"
  },
  fields: {
    title: "ملاعبك",
    emptyTitle: "لا توجد ملاعب بعد",
    emptySubtitle: "أرسل طلب إضافة ملعب من صفحة الحجوزات، وبعد موافقة الإدارة يظهر الملعب تلقائياً هنا.",
    needFirebase: "فعّل Firebase في البيئة لعرض الملاعب.",
    loadError: "تعذّر تحميل الملاعب",
    statusOpen: "مفتوح",
    statusClosed: "مغلق",
    statusMaintenance: "صيانة",
    menuTitle: "خيارات الملعب",
    actionClose: "إغلاق الملعب",
    actionMaintenance: "تحت الصيانة",
    actionOpen: "إعادة الفتح",
    actionManage: "حجز وإدارة المواعيد",
    manageHeader: "إدارة الملعب",
    selectDate: "التاريخ",
    availableSlots: "الأوقات المتاحة",
    noSlots: "لا توجد أوقات متاحة في هذا اليوم.",
    closedBanner: "الملعب مغلق — لا يمكن إضافة حجز.",
    maintenanceBanner: "الملعب تحت الصيانة — لا يمكن إضافة حجز.",
    bookingSection: "حجز يدوي",
    fieldBookingsSection: "حجوزات هذا الملعب",
    durationLabel: "المدة (دقيقة)",
    servicesLabel: "خدمات إضافية (افصل بينها بفاصلة)",
    servicesPlaceholder: "مثال: إضاءة، ماء، تسجيل",
    sourceLabel: "مصدر الحجز",
    sourceManual: "يدوي منك",
    sourcePlayer: "لاعب",
    playerNameLabel: "اسم اللاعب",
    playerNamePlaceholder: "اكتب اسم اللاعب",
    saveBooking: "تأكيد الحجز",
    bookingSaved: "تم حفظ الحجز",
    editBooking: "تعديل الحجز",
    deleteBooking: "حذف",
    confirmDeleteTitle: "حذف الحجز؟",
    confirmDeleteBody: "لن يمكن التراجع عن هذا الإجراء.",
    bookingUpdated: "تم تحديث الحجز",
    bookingDeleted: "تم حذف الحجز",
    pickSlotHint: "اختر وقتاً من القائمة أو اضبط الوقت يدوياً أدناه.",
    dashboardFieldBadge: "من لوحة التحكم",
    dashboardFieldBanner:
      "هذا الملعب يُدار من لوحة التحكم — لا يُضاف حجز يدوي من هنا. الحجوزات الظاهرة أدناه قادمة من الداشبورد.",
    dashboardSyncHint:
      "الحجز اليدوي يُحجز الوقت هنا ويُزامَن تلقائياً مع الداشبورد وتطبيق اللاعب لنفس الملعب.",
    dashboardBookingsReadOnly: "لتعديل حجوزات اللاعبين افتح تبويب الحجوزات.",
    fieldSizeShort: "الحجم",
    dashboardStatusLocked: "حالة ملاعب الداشبورد تُعدّل من لوحة التحكم فقط.",
    fieldDetailsTitle: "تفاصيل الملعب من قاعدة البيانات",
    fieldPhoneLabel: "الهاتف",
    fieldSuggestedPriceHint: "سعر مقترح للمدة المختارة (من بيانات الملعب)",
    fieldSlotsWindow: "نافذة الأوقات المعروضة: {{start}} — {{end}}",
    fieldPricePerHourHint: "سعر الساعة: {{price}} د.ع",
    fieldDetailsScreenTitle: "تفاصيل الملعب",
    shareField: "مشاركة",
    shareFieldMessage: "اطّلع على هذا الملعب في تطبيق الإدارة",
    heroDistanceLabel: "يبعد عنك:",
    heroDistanceUnknown: "—",
    heroPriceLabel: "سعر الحجز:",
    pricePerHourSuffix: "د.ع / ساعة",
    chooseTimeTitle: "اختر الوقت (من — إلى)",
    chooseTimeSub: "اختر وقت البداية؛ يُحسب وقت النهاية تلقائياً حسب المدة.",
    slotAvailable: "متاح",
    durationShoot1h: "ساعة",
    durationShoot1_5h: "ساعة ونص",
    durationShoot2h: "ساعتين",
    durationShoot3h: "3 ساعات",
    fieldDescriptionTitle: "وصف الملعب",
    fieldServicesTitle: "الخدمات المتوفرة",
    fieldSizeTitle: "حجم الملعب",
    ratingsTitle: "التقييمات",
    ratingCleanliness: "النظافة",
    ratingGrass: "جودة العشب",
    ratingLighting: "الإضاءة",
    addonsOptionalTitle: "إضافات اختيارية (قبل الدفع)",
    fieldOpenDaysTitle: "أيام العمل",
    timesAndDaysTitle: "الأوقات والأيام",
    timesAndDaysHint: "اختر يوم الحجز — تُعرض الأيام المتوافقة مع أيام عمل الملعب عند توفرها في قاعدة البيانات.",
    bookingDurationTitle: "مدة الحجز",
    paidServicesTitle: "الخدمات المدفوعة",
    extraPriceFormat: "+{{price}} د.ع",
    totalLabel: "المجموع",
    bookPaymentCta: "احجز — اختر طريقة الدفع",
    bookOnlyCta: "احجز",
    durationPricesTitle: "اختر مدة الحجز (السعر من قاعدة البيانات)",
    durationPriceHintHourly: "يُحسب من سعر الساعة عند عدم وجود سعر ثابت للمدة",
    ownerAdvancedSection: "إعدادات المالك والمزامنة",
    reviewsCount: "{{n}} تقييم"
  },
  accounts: {
    title: "حساباتك المالية",
    externalTotal: "إجمالي الوارد الخارجي",
    manualTotal: "إجمالي الوارد اليدوي",
    dailyIncomeTotal: "الوارد اليومي",
    dailyIncomeHint: "يُحدَّث كل يوم (24 ساعة)",
    monthlyIncome: "وارد هذا الشهر",
    expensesTotal: "إجمالي المصاريف",
    netProfit: "صافي الربح",
    dashboardSection: "لوحة مالية",
    movementTypeLabel: "نوع الحركة",
    typeExpense: "مصروف",
    typeManualBooking: "وارد يدوي (حجز)",
    typeExternal: "وارد خارجي",
    addMovement: "تسجيل حركة",
    amountLabel: "المبلغ",
    amountPlaceholder: "مثال: 150000",
    amountOrCalcHint: "أو احسب من المدة × السعر أدناه",
    noteLabel: "ملاحظة (اختياري)",
    notePlaceholder: "وصف قصير…",
    categoryLabel: "التصنيف (اختياري)",
    categoryPlaceholder: "مثال: صيانة، رواتب، مستلزمات",
    dateLabel: "التاريخ",
    datePlaceholder: "YYYY-MM-DD (افتراضي: اليوم)",
    hoursLabel: "المدة (ساعات)",
    hoursPlaceholder: "مثال: 1.5",
    pricePerHourLabel: "سعر الساعة (د.ع)",
    pricePerHourPlaceholder: "مثال: 80000",
    computedRevenue: "المحسوب",
    addExpense: "إضافة مصروف",
    addIncomeExternal: "وارد خارجي",
    addIncomeManual: "وارد يدوي",
    submitExpense: "إضافة مصروف",
    submitIncomeManual: "تسجيل وارد يدوي",
    submitIncomeExternal: "تسجيل وارد خارجي",
    recentTitle: "سجل الحركات",
    emptyMovements: "لا توجد حركات بعد.",
    savedToast: "تم حفظ الحركة",
    invalidAmount: "اكتب مبلغاً صحيحاً أكبر من صفر",
    invalidManualCalc: "أدخل مدة وسعر ساعة صحيحين، أو مبلغاً مباشراً",
    invalidDate: "صيغة التاريخ غير صحيحة — استخدم YYYY-MM-DD",
    currency: "د.ع",
    kindExpense: "مصروف",
    kindExternal: "وارد خارجي",
    kindManual: "وارد يدوي",
    kindBooking: "وارد تلقائي (حجز)",
    statusCompleted: "مكتمل",
    bookingIncomeAuto: "وارد من إنهاء الحجوزات (تلقائي)",
    summaryKpi: "صافي الربح",
    personLabel: "الاسم",
    cloudLedgerWriteFailed: "تعذّر رفع الحركة إلى السحابة",
    cloudLedgerWriteFailedHint: "تحقّق من الإنترنت وحاول مرة أخرى."
  },
  servicesHub: {
    title: "الخدمات",
    subtitle: "إدارة حسابك وخدماتك",
    walletTitle: "المحفظة",
    walletSub: "رصيدك والمعاملات",
    aboutTitle: "عن شوتها بزنس",
    aboutSub: "معلومات عن التطبيق",
    privacyTitle: "سياسة الخصوصية",
    privacySub: "حماية بياناتك",
    platformsTitle: "منصات شوتها بزنس",
    platformsSub: "تابعنا على المنصات",
    whatsappTitle: "واتساب",
    whatsappSub: "تواصل مباشر",
    websiteTitle: "الموقع الرسمي",
    websiteSub: "زيارة الموقع",
    linksNotSet: "روابط الدعم غير مُعدّة بعد",
    openLinkFailed: "تعذّر فتح الرابط",
    aboutToast: "Shoot'ha Business — منصة لإدارة الحجوزات والمدفوعات والتواصل.",
    platformsToast: "قريباً: روابط منصات شوتها بزنس"
  },
  platforms: {
    comingSoon: "قريباً",
    instagramTitle: "الانستجرام",
    instagramSub: "Shoot'ha",
    facebookTitle: "الفيس بوك",
    facebookSub: "Shoot'ha",
    tiktokTitle: "التيك توك",
    tiktokSub: "Shoot'ha",
    whatsappTitle: "الواتساب",
    whatsappSub: "تواصل مباشر",
    websiteTitle: "الموقع الرسمي",
    websiteSub: "زيارة الموقع",
    phoneTitle: "رقم الهاتف",
    phoneSub: "اضغط لعرض الرقم",
    phoneHint: "ضع رقم الهاتف في الإعدادات لاحقاً"
  },
  bookings: {
    today: "اليوم",
    upcoming: "القادم",
    past: "السابق",
    addBooking: "إضافة حجز",
    requestAddField: "طلب إضافة ملعب",
    requestAddFieldTitle: "طلب إضافة ملعب جديد",
    requesterNameLabel: "اسمك",
    requesterNamePlaceholder: "الاسم الثلاثي",
    fieldNameLabel: "اسم الملعب",
    fieldNamePlaceholder: "مثال: ملعب النخيل",
    cityLabel: "المدينة أو الحي",
    cityPlaceholder: "مثال: بغداد — مطلوب لطلب الملعب",
    provinceLabel: "المحافظة",
    provincePlaceholder: "اختر المحافظة",
    fieldTypeLabel: "نوع الملعب",
    fieldTypePlaceholder: "اختر نوع الملعب",
    fieldTypeFootball: "كرة قدم",
    fieldTypePadel: "بادل",
    fieldTypeBasketball: "كرة سلة",
    fieldTypeVolleyball: "كرة طائرة",
    notesLabel: "ملاحظات",
    notesPlaceholder: "مثال: الموقع، السعة، نوع الأرضية…",
    contactPhoneLabel: "رقم التواصل",
    contactPhonePlaceholder: "للتواصل معك عند الحاجة",
    contactPhonePlaceholderNational: "7xxxxxxxxx",
    submitFieldRequest: "إرسال الطلب",
    fieldRequestSuccess: "تم إرسال طلبك بنجاح",
    fieldRequestNeedBackend: "الخادم غير مفعّل بعد — ما نقدر نرسل الطلب الحين. جرّب لاحقاً بعد التفعيل.",
    fieldRequestValidation: "اكتب اسم الملعب",
    fieldRequestValidationPerson: "اكتب اسمك",
    fieldRequestValidationLocation: "اكتب المدينة أو المنطقة (الموقع)",
    fieldRequestValidationProvince: "اختر المحافظة",
    fieldRequestValidationFieldType: "اختر نوع الملعب",
    fieldRequestFirebaseNotConfigured: "Firebase غير مُعدّ — لا يمكن إرسال الطلب.",
    fieldRequestLoginRequired: "سجّل الدخول لإرسال الطلب إلى Firestore.",
    fieldRequestOwnerIdMissing: "تعذّر تحميل معرّف المالك. أعد تسجيل الدخول.",
    fieldRequestProfileIncomplete: "أكمل اسمك ورقم الهاتف في الملف الشخصي لإرسال الطلب.",
    requestIdSentHint: "رقم مرجعي يُرسل مع طلبك",
    accountIdHint: "رقم حسابك يظهر للإدارة تلقائياً",
    guestPreviewAccountHint: "رقم جلسة الزائر",
    guestSessionHint: "مرجع الجلسة",
    fieldRequestTableMissing: "ما نقدر نكمل الطلب — الخدمة غير جاهزة بعد.",
    emptyTitle: "لا توجد حجوزات",
    emptySubtitle: "أي حجز جديد راح يظهر هنا.",
    approve: "قبول",
    reject: "رفض",
    statusPending: "بالانتظار",
    statusApproved: "مقبول",
    statusRejected: "مرفوض",
    statusConfirmed: "مؤكد",
    statusCancelled: "ملغى",
    fieldLabel: "الملعب",
    totalPriceLabel: "السعر",
    durationLabel: "المدة",
    currencyShort: "د.ع",
    createdByOwner: "من المالك",
    createdByPlayer: "من اللاعب",
    sourceManualLabel: "حجز من قبل صاحب الملعب",
    /** سطر الاسم/المصدر لحجز المالك اليدوي في البطاقة */
    bookingByFieldOwnerLabel: "حجز من قبل صاحب الملعب",
    sourcePlayerPrefix: "من اللاعب: ",
    servicesLineLabel: "الخدمات",
    playerRequestedServicesLabel: "خدمات مطلوبة من اللاعب",
    servicesNotSpecified: "لم تُذكر",
    dashboardBookingSource: "حجز من لوحة التحكم",
    fieldSizeLabel: "حجم الملعب",
    paymentMethodLabel: "طريقة الدفع",
    paymentUnspecified: "غير محدد",
    paymentCash: "نقداً",
    paymentElectronic: "إلكتروني",
    paymentBankTransfer: "تحويل بنكي",
    paymentPos: "جهاز POS",
    paymentOwnerManual: "يدوي (تطبيق المالك)",
    paymentMethodCustomHint: "يمكنك تعديل النص أدناه إذا كانت القيمة قادمة من لوحة التحكم بصيغة أخرى.",
    playerPhoneLabel: "هاتف اللاعب",
    playerNameRequired: "اسم اللاعب مطلوب في الحجز اليدوي",
    playerPhoneRequired: "رقم هاتف اللاعب مطلوب في الحجز اليدوي",
    venueDurationHint: "القيمة ≤٢٤ تُحسب بالساعات، وإلا بالدقائق (كما في الداشبورد)",
    venueIdLabel: "معرّف الملعب",
    venueNameLabel: "اسم الملعب",
    bookingStatusLabel: "الحالة",
    noPlayerName: "بدون اسم لاعب",
    editBookingShort: "تعديل",
    deleteBookingShort: "حذف",
    loginRequiredBookings: "سجّل دخولك برقم الهاتف عشان تشوف حجوزاتك.",
    needBackendBookings: "عرض الحجوزات من الخادم غير مفعّل حالياً.",
    loadErrorBookings: "ما قدرنا نحمّل الحجوزات. تحقق من الإنترنت وحاول مرة ثانية.",
    emptyStateLoadTitle: "تعذّر عرض الحجوزات",
    emptyStateBackendTitle: "عرض الحجوزات غير مفعّل",
    noFieldsHint: "لا توجد ملاعب مربوطة بحسابك بعد.",
    selectField: "اختر الملعب",
    addedFieldsList: "الملاعب المضافة",
    changeField: "تغيير الملعب",
    selectedFieldShort: "الملعب",
    priceLabel: "السعر (دينار عراقي)",
    bookingSaved: "تم حفظ الحجز",
    statusUpdated: "تم تحديث الحالة",
    screenSubtitle: "متابعة طلبات ملعبك",
    statTapToFilter: "اضغط للتصفية",
    /** الصفحة الرئيسية — مطابقة تصميم Shoot'ha Business */
    homeWelcomeName: "مرحباً {{name}} ",
    homeWelcomeSub: "أهلاً بك في منصة شوّتها لإدارة الملاعب",
    homeAddBookingCta: "+ إضافة حجز",
    homeAddBookingCtaSub: "ابدأ بإضافة حجوزات ملعبك من هنا!",
    sectionBookingsToday: "حجوزات اليوم",
    sectionBookingsUpcoming: "حجوزات القادمة",
    sectionBookingsPast: "حجوزات السابقة",
    dateLabel: "التاريخ",
    datePlaceholder: "مثال: ٢٠٢٦-٠٤-٠٣",
    startTimeLabel: "وقت البداية",
    timePlaceholder: "مثال: ١٨:٠٠",
    durationMinutesLabel: "مدة الحجز",
    durationPlaceholder: "٦٠",
    durationOneHour: "ساعة",
    durationOneHourSub: "٦٠ دقيقة",
    durationOneHalfHour: "ساعة ونص",
    durationOneHalfHourSub: "٩٠ دقيقة",
    pricePlaceholder: "٧٥٠٠٠",
    modalCancel: "إلغاء",
    modalSave: "حفظ",
    modalCloseA11y: "إغلاق",
    phoneRequiredForGuestRequest: "الزائر لازم يكتب رقم هاتف للتواصل",
    fieldRequestSheetSubtitle: "املأ البيانات وراح نراجع طلبك ونتواصل معك.",
    fieldRequestStep1Title: "بياناتك واسم الملعب",
    fieldRequestStep2Title: "الموقع والتفاصيل",
    fieldRequestStep3Title: "التواصل والمراجعة",
    fieldRequestNext: "التالي",
    fieldRequestBack: "رجوع",
    fieldRequestGuestPhoneNote: "لازم رقم هاتف عشان نتواصل معك.",
    fieldRequestSummaryTitle: "ملخص طلبك",
    fieldRequestOwnerIdLabel: "معرّف المالك (من النظام)",
    fieldRequestOwnerIdHint: "يُرسل تلقائياً مع الطلب ولا يمكن تعديله.",
    scheduleInlineTitle: "جدول اليوم",
    scheduleInlineOpen: "فتح",
    postMatchTitle: "انتهت المباراة",
    postMatchSubtitle: "قيّم اللاعب وسجّل نهاية الحجز. يُحفظ التقييم في السحابة ويُضاف سعر الحجز للمالية.",
    ratePlayerLabel: "تقييم اللاعب",
    starsHint: "من نجمة واحدة إلى خمس",
    commentLabel: "ملاحظة (اختياري)",
    commentPlaceholder: "مثال: انضباط، تعامل…",
    submitPostMatch: "حفظ التقييم وإنهاء الحجز",
    postMatchSuccess: "تم حفظ التقييم وتسجيل المبلغ في المالية",
    postMatchAlreadyDone: "تم إنهاء هذا الحجز مسبقاً",
    postMatchNotFound: "تعذّر تحميل الحجز",
    postMatchError: "تعذّر الإكمال. تحقق من الاتصال والقواعد.",
    settledBadge: "منتهٍ",
    endMatchButton: "تقييم وإنهاء",
    postMatchPickRating: "اختر عدد النجوم",
    attendanceTitle: "تأكيد الحضور",
    attendanceAttended: "حضر",
    attendanceNoShow: "لم يحضر",
    attendanceDiscountHint:
      "يظهر هذا القسم تلقائياً قبل 15 دقيقة من موعد بداية الحجز. قبل «تقييم وإنهاء»: إن اخترت «لم يحضر» يُطبَّق خصم تلقائي ولا يُسجَّل إيراد لهذا الحجز في المالية.",
    attendanceSaved: "تم حفظ تأكيد الحضور",
    attendanceError: "تعذّر حفظ تأكيد الحضور. حاول مرة أخرى.",
    postMatchNoShowIncomeHint:
      "تم اختيار «لم يحضر» — لن يُضاف مبلغ هذا الحجز للمالية عند حفظ التقييم والإنهاء."
  },
  schedule: {
    title: "الجدول اليومي",
    openHint: "اضغط لعرض الجدول كاملاً",
    subtitle: "كل خانة نصف ساعة — نظام الحجز: ساعة أو ساعة ونص فقط.",
    backToBookings: "رجوع للحجوزات",
    empty: "لا يوجد حجز اليوم.",
    booked: "محجوز",
    available: "فاضي",
    slotHalfHour: "نصف ساعة"
  },
  notifications: {
    title: "الإشعارات",
    emptyTitle: "لا توجد إشعارات",
    emptySubtitle: "التنبيهات والتحديثات راح تظهر هنا.",
    loginRequiredSubtitle: "سجّل دخولك عشان تشوف إشعاراتك.",
    guestEmptyTitle: "الإشعارات غير متاحة",
    needBackendSync: "أضف مفاتيح Firebase في البيئة (EXPO_PUBLIC_FIREBASE_*) لتلقّي الإشعارات من السحابة.",
    emptyStateBackendTitle: "Firebase غير مُعدّ للإشعارات",
    loadError: "ما قدرنا نحمّل الإشعارات. حاول مرة ثانية.",
    markAllRead: "تعليم الكل كمقروء",
    allUpdatedToast: "تم التحديث",
    unreadSuffix: "غير مقروء",
    noNewAlerts: "لا توجد تنبيهات جديدة",
    typeBooking: "حجز",
    typeApproval: "موافقة",
    typeSystem: "تنبيه",
    fieldRequestApprovedTitle: "تم قبول طلب إضافة الملعب",
    fieldRequestApprovedBody: "الملعب «{name}» — يمكنك متابعة الإعداد من الحساب أو الدعم.",
    fieldRequestRejectedTitle: "تم رفض طلب إضافة الملعب",
    fieldRequestRejectedBody: "الملعب «{name}». للاستفسار تواصل مع الدعم.",
    newBookingToastTitle: "حجز جديد",
    newBookingToastSub: "اضغط للانتقال إلى الحجوزات",
    openBookingHint: "اضغط للانتقال إلى الحجز في قائمة الحجوزات",
    bookingOpenedFromNotification: "تم عرض الحجز",
    bookingNotFound: "تعذّر العثور على الحجز في القائمة بعد التحديث"
  },
  deleteAccount: {
    navTitle: "حذف الحساب",
    title: "حذف الحساب",
    phoneSubtitle: "أدخل رقم الهاتف المسجّل على حسابك لإرسال رمز التحقق.",
    sendOtp: "إرسال رمز التحقق",
    phoneMismatch: "الرقم لا يطابق رقم حسابك الحالي.",
    noSession: "لا يوجد حساب نشط.",
    otpNavTitle: "رمز التحقق",
    otpTitle: "أدخل رمز التحقق",
    otpSubtitle: "اكتب الرمز المرسل إلى هاتفك لتأكيد حذف الحساب.",
    confirmDelete: "تأكيد حذف الحساب",
    success: "تم حذف حسابك.",
    finalWarning: "بعد التأكيد يُحذف الحساب نهائياً ولا يمكن استعادته.",
    backToProfile: "العودة للحساب",
    deleteFailed: "تعذّر إكمال حذف الحساب. حاول مرة أخرى أو تواصل مع الدعم."
  },
  profile: {
    title: "الحساب",
    name: "الاسم",
    phone: "رقم الهاتف",
    editProfile: "تعديل الحساب",
    requestFieldChange: "طلب تعديل بيانات الملعب",
    reportIssue: "إبلاغ عن مشكلة",
    appearance: "المظهر",
    themeLight: "فاتح",
    themeDark: "داكن",
    themeHint: "وضع مريح للقراءة نهاراً وليلاً — يُحفظ تلقائياً على جهازك.",
    save: "حفظ",
    cancel: "إلغاء",
    dataSection: "بياناتك",
    settingsSection: "الإعدادات",
    guestName: "زائر",
    saveSuccessToast: "تم حفظ التعديلات",
    whatsappSupport: "تواصل عبر واتساب",
    termsLink: "الشروط والأحكام",
    supportLinksNotSet: "لم يُضبط بعد — يمكن ضبطه من لوحة الإدارة أو ملف البيئة.",
    openWhatsappFailed: "تعذّر فتح واتساب. تحقق من الرقم أو الرابط.",
    openTermsFailed: "تعذّر فتح الرابط. أضف عنواناً يبدأ بـ https://"
  },
  requests: {
    fieldChangeTitle: "طلب تعديل بيانات الملعب",
    issueTitle: "إبلاغ عن مشكلة",
    placeholder: "اكتب التفاصيل هنا…",
    send: "إرسال",
    success: "تم إرسال طلبك"
  },
  common: {
    error: "صار خطأ غير متوقع",
    pullToRefresh: "اسحب للتحديث",
    loading: "جارٍ التحميل…",
    tryAgain: "إعادة المحاولة",
    cancel: "إلغاء",
    done: "تم"
  },
  errors: {
    backendLater: "هذه الخدمة راح تتفعّل لاحقاً مع الخادم.",
    useAuthContext: "خطأ في تهيئة الجلسة. أعد فتح التطبيق.",
    useSettingsContext: "خطأ في الإعدادات. أعد فتح التطبيق.",
    firebaseNotConfigured: "Firebase غير مُعدّ: أضف مفاتيح EXPO_PUBLIC_FIREBASE_* في ملف البيئة.",
    firebaseRecaptchaNotReady: "جاري تهيئة التحقق. حاول مرة ثانية بعد لحظة.",
    firebaseSendOtpFailed: "تعذّر إرسال رمز التحقق. تحقق من الرقم ومن إعداد Firebase.",
    firebaseOtpSessionExpired: "انتهت جلسة التحقق. ارجع وأعد إرسال الرمز.",
    phoneMustStartWithPlus: "اكتب الرقم بصيغة دولية تبدأ بـ + (مثال: +9647700000000).",
    phoneInvalidE164: "صيغة الرقم غير صحيحة. استخدم + متبوعاً بكود الدولة ثم الرقم (حتى 15 رقماً).",
    phoneNationalInvalid:
      "رقم الهاتف المحلي غير صحيح. للعراق (+964): 10 أرقام تبدأ بـ 7 (مثال: 7712345678)."
  }
};
